import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { Header, NavBar, Content } from "../components";
import request from "../Common/navbar";
import { MOVIE_URL } from "../Common/url";

const Home = (props: any) => {
    return (
        <div>
            <Head>
                <title>Hulu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <NavBar />

            <Content data={props.data.results} />
        </div>
    );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
    const genre = context.query.genre as string;
    const data = await (await fetch(`${MOVIE_URL}${request[genre]?.url || request.fetchTrending.url}`)).json();
    return {
        props: {
            data,
        },
    };
};
